export const API_PREFIX = 'api';

export const API_ROUTES = {
  HEALTH: '/health',
  HEALTH_READY: '/health/ready',
  DOCS: '/docs',
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGIN: '/auth/login',
  AUTH_REFRESH: '/auth/refresh',
  AUTH_LOGOUT: '/auth/logout',
  AUTH_ME: '/auth/me',
  TENANT_CURRENT: '/tenants/current',
  USERS: '/users',
  DASHBOARD_SUMMARY: '/dashboard/summary',
  LOCATIONS_TREE: '/locations/tree',
  LOCATIONS_COUNTRIES: '/locations/countries',
  LOCATIONS_STATES: '/locations/states',
  LOCATIONS_CITIES: '/locations/cities',
  BRANCHES: '/branches',
  HRM_DEPARTMENTS: '/hrm/departments',
  HRM_DESIGNATIONS: '/hrm/designations',
  HRM_ROLES: '/hrm/roles',
  HRM_EMPLOYEES: '/hrm/employees',
  HRM_LEAVE_TYPES: '/hrm/leave-types',
  HRM_LEAVES: '/hrm/leaves',
  HRM_ATTENDANCE: '/hrm/attendance',
  HRM_WORK_INFO: '/hrm/work-info',
  HRM_PAYROLL: '/hrm/payroll',
  HRM_PAYSLIPS: '/hrm/payslips',
  LEADS: '/leads',
  LEAD_REMINDERS: '/leads/reminders',
  C2C_DASHBOARD: '/dashboard/c2c',
  WEBSITE_BANKS: '/website/banks',
  WEBSITE_BANKS_PUBLIC: '/website/banks/public',
  WEBSITE_ENQUIRIES: '/website/enquiries',
  WEBSITE_ENQUIRIES_PUBLIC: '/website/enquiries/public',
  WEBSITE_ANNOUNCEMENTS: '/website/announcements',
  WEBSITE_BIRTHDAYS: '/website/birthdays/today',
  UPLOADS_IMAGE: '/uploads/image',
} as const;
