export const PERMISSIONS = {
  TENANT_VIEW: 'tenant.view',
  TENANT_UPDATE: 'tenant.update',
  USER_VIEW: 'user.view',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DEACTIVATE: 'user.deactivate',
  ROLE_VIEW: 'role.view',
  ROLE_ASSIGN: 'role.assign',
  ROLE_MANAGE: 'role.manage',
  INTEGRATION_VIEW: 'integration.view',
  INTEGRATION_ENABLE: 'integration.enable',
  INTEGRATION_DISABLE: 'integration.disable',
  INTEGRATION_CONFIGURE: 'integration.configure',
  INTEGRATION_TEST: 'integration.test',
  INTEGRATION_VIEW_LOGS: 'integration.view_logs',
  INTEGRATION_MANAGE_CREDENTIALS: 'integration.manage_credentials',
  BILLING_PAYMENT_CREATE: 'billing.payment.create',
  BILLING_PAYMENT_REFUND: 'billing.payment.refund',
  NOTIFICATION_SEND: 'notification.send',
  NOTIFICATION_MANAGE_TEMPLATES: 'notification.manage_templates',
  API_KEY_CREATE: 'api_key.create',
  API_KEY_REVOKE: 'api_key.revoke',
  WEBHOOK_CREATE: 'webhook.create',
  WEBHOOK_DELETE: 'webhook.delete',
  LOCATION_VIEW: 'location.view',
  LOCATION_MANAGE: 'location.manage',
  BRANCH_VIEW: 'branch.view',
  BRANCH_MANAGE: 'branch.manage',
  HRM_EMPLOYEE_VIEW: 'hrm.employee.view',
  HRM_EMPLOYEE_CREATE: 'hrm.employee.create',
  HRM_EMPLOYEE_UPDATE: 'hrm.employee.update',
  HRM_EMPLOYEE_DEACTIVATE: 'hrm.employee.deactivate',
  HRM_LEAVE_VIEW: 'hrm.leave.view',
  HRM_LEAVE_MANAGE: 'hrm.leave.manage',
  HRM_ATTENDANCE_VIEW: 'hrm.attendance.view',
  HRM_ATTENDANCE_MANAGE: 'hrm.attendance.manage',
  LEAD_VIEW: 'lead.view',
  LEAD_CREATE: 'lead.create',
  LEAD_UPDATE: 'lead.update',
  LEAD_IMPORT: 'lead.import',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const TENANT_OWNER_PERMISSIONS: PermissionKey[] = Object.values(PERMISSIONS);

export const TENANT_ADMIN_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.TENANT_VIEW,
  PERMISSIONS.TENANT_UPDATE,
  PERMISSIONS.USER_VIEW,
  PERMISSIONS.USER_CREATE,
  PERMISSIONS.USER_UPDATE,
  PERMISSIONS.ROLE_VIEW,
  PERMISSIONS.ROLE_ASSIGN,
  PERMISSIONS.ROLE_MANAGE,
  PERMISSIONS.INTEGRATION_VIEW,
  PERMISSIONS.LOCATION_VIEW,
  PERMISSIONS.LOCATION_MANAGE,
  PERMISSIONS.BRANCH_VIEW,
  PERMISSIONS.BRANCH_MANAGE,
  PERMISSIONS.HRM_EMPLOYEE_VIEW,
  PERMISSIONS.HRM_EMPLOYEE_CREATE,
  PERMISSIONS.HRM_EMPLOYEE_UPDATE,
  PERMISSIONS.HRM_EMPLOYEE_DEACTIVATE,
  PERMISSIONS.HRM_LEAVE_VIEW,
  PERMISSIONS.HRM_LEAVE_MANAGE,
  PERMISSIONS.HRM_ATTENDANCE_VIEW,
  PERMISSIONS.HRM_ATTENDANCE_MANAGE,
  PERMISSIONS.LEAD_VIEW,
  PERMISSIONS.LEAD_CREATE,
  PERMISSIONS.LEAD_UPDATE,
  PERMISSIONS.LEAD_IMPORT,
];

export const TENANT_MEMBER_PERMISSIONS: PermissionKey[] = [PERMISSIONS.TENANT_VIEW];
